-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 15:05:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trailerflix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trailerflix` ;

-- -----------------------------------------------------
-- Schema trailerflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trailerflix` DEFAULT CHARACTER SET utf8 ;
USE `trailerflix` ;

-- -----------------------------------------------------
-- Table `trailerflix`.`Categorías`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`Categorías` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoriaOriginal_UNIQUE` (`idCategoria` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trailerflix`.`Contenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`Contenidos` (
  `idContenido` INT NOT NULL AUTO_INCREMENT,
  `poster` VARCHAR(240) NULL,
  `titulo` VARCHAR(120) CHARACTER SET 'utf8' NULL,
  `idCategoria` INT NOT NULL,
  `resumen` VARCHAR(500) CHARACTER SET 'utf8' NULL,
  `temporadas` INT NULL,
  `trailer` VARCHAR(240) NULL,
  PRIMARY KEY (`idContenido`),
  UNIQUE INDEX `idContenidoOriginal_UNIQUE` (`idContenido` ASC) ,
  INDEX `idCategoriaa_idx` (`idCategoria` ASC) ,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `trailerflix`.`Categorías` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trailerflix`.`Géneros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`Géneros` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `idGeneroOriginal_UNIQUE` (`idGenero` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trailerflix`.`ContenidoGenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`ContenidoGenero` (
  `idContenidoGenero` INT NOT NULL AUTO_INCREMENT,
  `idContenido` INT NOT NULL,
  `idGenero` INT NOT NULL,
  PRIMARY KEY (`idContenidoGenero`),
  UNIQUE INDEX `idContenidoGenero_UNIQUE` (`idContenidoGenero` ASC) ,
  INDEX `idContenidooo_idx` (`idContenido` ASC) ,
  INDEX `idGeneroo_idx` (`idGenero` ASC) ,
  CONSTRAINT `idContenido`
    FOREIGN KEY (`idContenido`)
    REFERENCES `trailerflix`.`Contenidos` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idGenero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `trailerflix`.`Géneros` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trailerflix`.`Actores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`Actores` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(240) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idActor`),
  UNIQUE INDEX `idActor_UNIQUE` (`idActor` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trailerflix`.`ContenidoActor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trailerflix`.`ContenidoActor` (
  `idContenidoActor` INT NOT NULL AUTO_INCREMENT,
  `idContenido` INT NOT NULL,
  `idActor` INT NOT NULL,
  PRIMARY KEY (`idContenidoActor`),
  UNIQUE INDEX `idContenidoActor_UNIQUE` (`idContenidoActor` ASC) ,
  INDEX `idContenidoo_idx` (`idContenido` ASC) ,
  INDEX `idActorr_idx` (`idActor` ASC) ,
  CONSTRAINT `idContenidoCA`
    FOREIGN KEY (`idContenido`)
    REFERENCES `trailerflix`.`Contenidos` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idActorCA`
    FOREIGN KEY (`idActor`)
    REFERENCES `trailerflix`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
